MODEL:
  META_ARCHITECTURE: "YOLOF"
  BACKBONE:
    NAME: "build_resnet_backbone"
  RESNETS:
    OUT_FEATURES: ["res5"]
  YOLOF:
    DECODER:
      NUM_CLASSES: 20
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
DATALOADER:
  NUM_WORKERS: 8
SOLVER:
  IMS_PER_BATCH: 64
  BASE_LR: 0.12
  WARMUP_FACTOR: 0.00066667
  WARMUP_ITERS: 2
  STEPS: (0.6, 0.9)
  MAX_ITER: 10
  CHECKPOINT_PERIOD: 1
INPUT:
  MIN_SIZE_TRAIN: (800,)
