_BASE_: "yolof_R_50_DC5_1x.yaml"

SOLVER:
  BASE_LR: 0.0035
  WEIGHT_DECAY: 0.0008
  MAX_ITER: 12
  WARMUP_ITERS: 1
  STEPS: (0.66, 0.88)
  GAMMA: 0.1
  CHECKPOINT_PERIOD: 1

INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MAX_SIZE_TRAIN: 1333

  JITTER_CROP:
    ENABLED: true
  DISTORTION:
    ENABLED: true
  MOSAIC:
    ENABLED: true

DATALOADER:
  NUM_WORKERS: 4

SEED: 42

OUTPUT_DIR: "output/soup_09"
