_BASE_: "yolof_R_50_DC5_1x.yaml"

SOLVER:
  BASE_LR: 0.009  # Very high
  WEIGHT_DECAY: 0.0007
  MAX_ITER: 8  # 24 epochs
  WARMUP_ITERS: 0.5
  STEPS: (0.66, 0.88)
  GAMMA: 0.1

INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MAX_SIZE_TRAIN: 1333
  
  CUTMIX:
    ENABLED: True
    ALPHA: 0.7
    PROB: 0.6

DATALOADER:
  NUM_WORKERS: 4

SEED: 42

OUTPUT_DIR: "output/soup_11"
