_BASE_: "yolof_R_50_DC5_1x.yaml"

SOLVER:
  BASE_LR: 0.0008
  WEIGHT_DECAY: 0.0003
  MAX_ITER: 16  # 48 epochs
  WARMUP_ITERS: 1
  STEPS: (0.66, 0.88)
  GAMMA: 0.1
  
  # Cosine annealing
  LR_SCHEDULER_NAME: "WarmupCosineLR"

INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  MAX_SIZE_TRAIN: 1333

  DISTORTION:
    ENABLED: True
  MOSAIC:
    ENABLED: True

DATALOADER:
  NUM_WORKERS: 4

SEED: 42

OUTPUT_DIR: "output/soup_07"